set -o vi
# Make C-l clear the screen in insert mode
bind -m vi-insert "\C-l":clear-screen

# Check update LINES and COLUMNS after each command based on window size
shopt -s checkwinsize
# Use ** to match zero or more subdirectories
shopt -s globstar

# Don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth
HISTSIZE=1000
HISTFILESIZE=2000
# Append to the history file, don't overwrite it
shopt -s histappend

# Set colorful prompt
case "$TERM" in
  *color|alacritty|xterm-kitty) color_prompt=true ;;
esac

if [ "$color_prompt" ]; then
  PS1='\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
  PS1='\u@\h:\w\$ '
fi
