{ pkgs, lib, ... }:

let
  secrets = import ../secrets.nix;
in
{
  users = {
    mutableUsers = false;
    users = {

      nprin = {
        name = "nprin";
        # Can be generated by 'mkpasswd -m sha-512'
        initialHashedPassword = secrets.users.nprin.hashedPassword;
        isNormalUser = true;
        uid = 1000;
        extraGroups = [
          "wheel"
          "audio"
          "video"
          "networkmanager"
          "docker"
          "vboxusers"
        ];
        createHome = true;
        home = "/home/nprin";
        shell = pkgs.bashInteractive;
      };

    };
  };
}
