set-option global ui_options ncurses_assistant=cat ncurses_enable_mouse=false

colorscheme desertex

add-highlighter global/ show-matching

set-option global grepcmd 'rg --column'
set-face global search +bi
add-highlighter global/ dynregex '%reg{/}' 0:+u

# Add color column
# add-highlighter global/ column '%opt{autowrap_column}' default,white

# Relative line numbering
hook global WinCreate ^[^*]+$ %{ add-highlighter window/ number-lines -relative -hlcursor -min-digits 2 }

# Default indent settings
set-option global tabstop 4
set-option global indentwidth 4
set-option global aligntab false

# Enable editor config
hook global BufOpenFile .* %{ editorconfig-load }
hook global BufNewFile .* %{ editorconfig-load }

# Improve default behavior of 'x' and 'X'
define-command -params 1 extend-line-down %{
    exec "<a-:>%arg{1}X"
}
define-command -params 1 extend-line-up %{
    exec "<a-:><a-;>%arg{1}K<a-;>"
    try %{
        exec -draft ';<a-K>\n<ret>'
        exec X
    }
    exec '<a-;><a-X>'
}
map global normal x ':extend-line-down %val{count}<ret>'
map global normal X ':extend-line-up %val{count}<ret>'

# Mappings
evaluate-commands %sh{
    printf "map global user -docstring 'evaluate' e 'y:<c-r>\"<ret>'"
}

# System clipboard handling
evaluate-commands %sh{
    copy="xclip -sel clip -i"
    paste="xclip -sel clip -o"
    printf "map global user -docstring 'paste (before) from clipboard' P '!%s<ret>'\n" "$paste"
    printf "map global user -docstring 'paste (after) from clipboard' p '<a-!>%s<ret>'\n" "$paste"
    printf "map global user -docstring 'yank to clipboard' y '<a-|>%s<ret>:echo -markup %%{{Information}copied selection to X11 clipboard}<ret>'\n" "$copy"
    printf "map global user -docstring 'replace from clipboard' R '|%s<ret>'\n" "$paste"
}

# Math/increment/decrement
map global normal = ':prompt math: %{exec "a%val{text}<lt>esc>|bc<lt>ret>"}<ret>'
map global user -docstring 'increment selection' <plus>  ':exec "<lt>a-i>na+1<lt>esc>|bc<lt>ret>"<ret>'
map global user -docstring 'decrement selection' <minus> ':exec "<lt>a-i>na-1<lt>esc>|bc<lt>ret>"<ret>'

# Adjust indent on the fly
define-command -params 1 adjust-indentation %{
    set-option buffer tabstop "%arg{1}"
    set-option buffer indentwidth "%arg{1}"
}
map global user -docstring 'adjust indent' i ':prompt indent: %{adjust-indentation "%val{text}"}<ret>'

# Language-specific options
hook global WinSetOption filetype=haskell %{
    ctags-enable-autoinfo
    hook global InsertChar \t %{ exec -draft -itersel h@ }
}
hook global WinSetOption filetype=(nix|haskell) %{
    adjust-indentation 2
}

# Plugin config
# smarttab.kak
hook global WinSetOption filetype=.* %{
    expandtab
}
# fzf.kak
require-module fzf
map global normal <c-p> ': fzf-mode<ret>'
map global normal <c-g> ': fzf-vcs-mode<ret>g'

# LSP config
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(haskell|typescript|python|sh|bash|tex) %{
  lsp-enable-window
  lsp-auto-hover-enable
}
map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
# Python
set-option global lsp_server_configuration pyls.plugins.pydocstyle.enabled=false pyls.plugins.pycodestyle.enable=true pyls.plugins.pycodestyle.ignore=["E111","E501","E302","W391"]
