owner = "nprindle"
fullName = "nprindle"
email = "nprindle18@gmail.com"

license = "MIT"
cabal = true
stack = false

gitignore = [
  "result",
  "dist*/",
  ".ghc*",
  ".cabal*",
  "*.config",
]

github = true
noUpload = true

lib = true
exe = true
test = false
bench = false

ghc-options = [
  "-Wall",
  "-O2",
]
